// This is visual metadata only. Captions are intentionally generated by the
// vision model at request time and are never attached to curated images.
export type CuratedImage = {
  title: string;
  tags: string[];
  imageUrl: string;
};

export const curatedImages: CuratedImage[] = [
  {
    title: "Blank Stare",
    tags: ["reaction", "deadpan", "exhausted", "study", "college"],
    imageUrl: "/reactions/blank-stare.png",
  },
  {
    title: "Phone Shock",
    tags: ["reaction", "shocked", "phone", "deadline", "student"],
    imageUrl: "/reactions/phone-shock.png",
  },
  {
    title: "Academic Victory",
    tags: ["reaction", "celebration", "win", "homework", "relief"],
    imageUrl: "/reactions/celebration.png",
  },
  {
    title: "Academic Panic",
    tags: ["reaction", "confused", "panic", "professor", "studying"],
    imageUrl: "/reactions/academic-panic.png",
  },
  {
    title: "Caught Peeking",
    tags: ["reaction", "hiding", "awkward", "late", "submission"],
    imageUrl: "/reactions/peek.png",
  },
  {
    title: "Financial Damage",
    tags: ["reaction", "broke", "sad", "nyc", "coffee"],
    imageUrl: "/reactions/broke.png",
  },
];
